ARTICLES_URL = "https://blog.yelp.com/"
EVENTS_URL = "https://www.yelp.com/events"
ACTIVITIES_URL = "https://www.yelp.com/"
CHROME_EXECUTABLE_PATH = "/usr/bin/chromedriver"
NO_EMAILS_FOUND = "No emails found"
EMAILS_CONSTANT = "emails"
EMAIL_REGEX = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
PRODUCTS_CSV_FILE = 'products.csv'
ARTICLES_CSV = 'articles.csv'
ACTIVITIES_CSV = 'activities.csv'
EVENTS_CSV = 'events.csv'
EMAILS_CSV = 'emails.csv'
