ARTICLES_URL = "https://blog.yelp.com/"
EVENTS_URL = "https://www.yelp.com/events"
ACTIVITIES_URL = "https://www.yelp.com/"
CHROME_EXECUTABLE_PATH = "/usr/bin/chromedriver"
NO_EMAILS_FOUND = "No emails found"
EMAILS_CONSTANT = "emails"
EMAIL_REGEX = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
PRODUCTS_CSV_FILE = 'products.csv'
ARTICLES_CSV = 'articles.csv'
ACTIVITIES_CSV = 'activities.csv'
EVENTS_CSV = 'events.csv'
EMAILS_CSV = 'emails.csv'
DATA_RECEIVED = 'Data received Successfully!'
DRIVER_CREATION_FAILURE = 'Chrome driver creation failure!!'
PAGE_RECEIVED = 'Driver received page successfully!!'
PAGE_NOT_FOUND = 'Driver page not found!'
TAB_OPENED = 'New tab opened successfully!'
ERROR_IN_NEW_TAB = 'Error occurred in opening new tab!'
ELEMENT_HOVERED = 'Element Hovered Successfully!'
ERROR_IN_HOVERING = 'Error occurred in hovering element!'
RETURNED_TO_TAB = 'Returned to tab 0 successfully!'
ERROR_SHIFTING_TAB = 'Error occurred shifting tab!'
DRIVER_QUIT = 'Driver quit successfully!'
STATUS_CODE = 'status_code'
MSG = 'msg'
CONNECTION_INTERRUPTED = '"Connection interrupted"'
